#!/bin/bash

# Find out script's dir, resolving any links to the script itself
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR/..
if [[ ! -z `ls lib/*.o[0-9] 2> /dev/null` ]]; then rm lib/*.o[0-9]; fi
gsc -e '(begin (include "/data/projects/scheme-prelude/src/prelude.scm")
(compile-file "module.scm" output: "sdl2.o1" cc-options: "-w -I/usr/local/include/SDL2" ld-options: "-L/usr/local/lib -lSDL2")
)'

if [[ ! -d lib ]]; then mkdir lib; fi
mv *.o[0-9] lib/
